### ISSUE TITLE
Are there plans to support asynchrony?

### ISSUE THREAD

**Issue by zy7y** [pycasbin/async-sqlalchemy-adapter#1]
as title, Build with SQLAlchemy and the casbin asynchronous version

**Comment by hsluoyz** [comment]
@Nekotoxin

**Comment by Nekotoxin** [comment]
> @Nekotoxin

I think we need to create a new repo, such as async-sqlalchemy-adapter. So it will be made for the async version of [asynccasbin](https://github.com/chapagainmanoj/asynccasbin),what do you think?

**Comment by hsluoyz** [comment]
@Nekotoxin created: https://github.com/pycasbin/async-sqlalchemy-adapter

BTW, we should also provide an official async version of PyCasbin based on: https://github.com/chapagainmanoj/asynccasbin

@leeqvip what name do you suggest?

**Comment by leeqvip** [comment]
> @Nekotoxin created: https://github.com/pycasbin/async-sqlalchemy-adapter
> 
> BTW, we should also provide an official async version of PyCasbin based on: https://github.com/chapagainmanoj/asynccasbin
> 
> @leeqvip what name do you suggest?

Just use this name.

**Comment by Nekotoxin** [comment]
@hsluoyz hi. we need to create a repo of asynccasbin. I will first implement the asynccasbin, then implement the async-sqlalchemy-adapter.

**Comment by hsluoyz** [comment]
@Nekotoxin done: https://github.com/casbin/async-pycasbin

**Comment by wu-clan** [comment]
Is there any progress on the related projects?
