### ISSUE TITLE
Errors Caused by the Deprecated Query API with Sqlalchemy 2.0 and Async

### ISSUE THREAD

**Issue by ChenHaolinOlym** [pycasbin/async-sqlalchemy-adapter#8]
When using sqlalchemy 2.0 with the async adapter, I'm getting `AttributeError: 'AsyncSession' object has no attribute 'query'` because the not supported `session.query`

Do you have any plans to upgrade the code to Sqlalchemy 2.0 style so that 2.0 with async is supported?

**Comment by hsluoyz** [comment]
@ChenHaolinOlym hi, can you make a PR?

**Comment by hsluoyz** [comment]
@BustDot
